name = "wheniswan-fetcher"
main = "src/worker.ts"
compatibility_date = "2023-07-10"
account_id = "f55b85c8a963663b11036975203c63c0"


# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/platform/services
# [[services]]
# binding = "MY_SERVICE"
# service = "/api/*"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
[[durable_objects.bindings]]
name = "WHENISWAN_FETCHER"
class_name = "FetcherObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["FetcherObject"]


